(()=>{'use strict';
const battle=document.querySelector('#battle'),msg=document.querySelector('#battlemsg'),commands=document.querySelector('#battlecommands')||document.querySelector('.battlecommands'),hero=document.querySelector('#battleHero').getContext('2d'),slime=document.querySelector('#battleSlime').getContext('2d');
hero.imageSmoothingEnabled=false;slime.imageSmoothingEnabled=false;
let active=false,enemyHp=0,enemyMax=0,hp=100,maxHp=100,mp=30,maxMp=30,currentEnemy=null,defending=false,submenu='';
let stats={attack:12,defense:3};
const spells=[
 {level:1,name:'Faísca Arcana',cost:4,damage:15},
 {level:2,name:'Chama Arcana',cost:7,damage:25},
 {level:3,name:'Lança de Gelo',cost:10,damage:38},
 {level:4,name:'Explosão Estelar',cost:14,damage:54},
 {level:5,name:'Ruptura Astral',cost:18,damage:73},
 {level:6,name:'Lúmen Absoluto',cost:23,damage:98}
];
function pixel(c,x,y,w,h,col){c.fillStyle=col;c.fillRect(x,y,w,h)}
function drawHero(){hero.clearRect(0,0,256,256);pixel(hero,55,205,145,18,'#17243b');pixel(hero,83,108,92,86,'#344b89');pixel(hero,94,119,70,67,'#7196e7');pixel(hero,82,145,20,45,'#d9e7ff');pixel(hero,156,145,20,45,'#d9e7ff');pixel(hero,95,185,25,42,'#263759');pixel(hero,139,185,25,42,'#263759');pixel(hero,88,219,38,14,'#d9caff');pixel(hero,135,219,38,14,'#d9caff');pixel(hero,81,43,96,76,'#f1c9ad');pixel(hero,70,31,116,38,'#6dc8ff');pixel(hero,66,51,24,69,'#6dc8ff');pixel(hero,166,51,24,61,'#6dc8ff');pixel(hero,95,72,14,18,'#273553');pixel(hero,148,72,14,18,'#273553');pixel(hero,99,76,6,8,'#fff');pixel(hero,152,76,6,8,'#fff');pixel(hero,119,96,21,5,'#cf7c83');pixel(hero,101,17,38,18,'#ffdf8d');pixel(hero,113,4,15,31,'#fff0b5')}
function drawEnemy(){slime.clearRect(0,0,256,256);const id=currentEnemy?.id==='goblinSoldier'?'goblin-soldier':(currentEnemy?.id||'slime');const art=new Image();art.onload=()=>{if(active){slime.clearRect(0,0,256,256);slime.drawImage(art,0,0,256,256)}};art.onerror=()=>{slime.clearRect(0,0,256,256);pixel(slime,37,206,184,15,'#17243b');slime.fillStyle='#477db4';slime.beginPath();slime.moveTo(38,190);slime.lineTo(48,130);slime.lineTo(82,91);slime.lineTo(124,73);slime.lineTo(169,91);slime.lineTo(207,132);slime.lineTo(218,190);slime.closePath();slime.fill()};art.src='sprites/'+id+'.svg'}
function say(t){msg.textContent=t}
function state(){return window.lumenGame?.getState?.()||{}}
function sync(){window.lumenGame?.setVitals?.(hp,mp)}
function render(){
 const p=state();hp=Math.max(0,Math.min(maxHp,hp));mp=Math.max(0,Math.min(maxMp,mp));
 document.querySelector('#bHpText').textContent=hp+' / '+maxHp;document.querySelector('#bHpBar').style.width=100*hp/maxHp+'%';
 document.querySelector('#bMpText').textContent=mp+' / '+maxMp;document.querySelector('#bMpBar').style.width=100*mp/maxMp+'%';
 document.querySelector('#eHpText').textContent=Math.max(0,enemyHp)+' / '+enemyMax;document.querySelector('#eHpBar').style.width=100*Math.max(0,enemyHp)/enemyMax+'%';
 document.querySelector('#bPotions').textContent=p.potions??1;document.querySelector('#bLevel').textContent=p.level||1;
 if(submenu==='abilities'){commands.innerHTML='<button data-action="back">← Voltar</button>'+spells.filter(s=>s.level<=(p.level||1)).map(s=>'<button data-spell="'+s.level+'" '+(mp<s.cost?'disabled':'')+'>✧ '+s.name+'<small>'+s.cost+' MP · '+s.damage+' dano base</small></button>').join('')}
 else if(submenu==='items'){const life=p.potions||0,mana=window.lumenShop?.inventory?.manaPotions||0;commands.innerHTML='<button data-item="life" '+(!life||hp>=maxHp?'disabled':'')+'>♥ Poção de vida<small>Recupera até 45 HP · '+life+' disponível(is)</small></button><button data-item="mana" '+(!mana||mp>=maxMp?'disabled':'')+'>✧ Poção de mana<small>Recupera até 12 MP · '+mana+' disponível(is)</small></button><button data-action="back">← Voltar</button>'}
 else{commands.innerHTML='<button data-action="attack">⚔ Atacar<small>Dano físico</small></button><button data-action="defend">🛡 Defender<small>Reduz o próximo dano</small></button><button data-action="abilities">✧ Habilidades<small>'+spells.filter(s=>s.level<=(p.level||1)).length+' magia(s) aprendida(s)</small></button><button data-action="items">♥ Itens<small>Poções de vida e mana</small></button><button data-action="escape">↗ Fugir<small>Tentar escapar</small></button>'}
}
function start(enemy){if(active)return;const p=state();currentEnemy=enemy||(window.lumenGame?.getEnemies?.()||[]).find(e=>e.alive&&e.unlocked)||{id:'slime',name:'Slime',level:1,hp:24,maxHp:24,attack:5,defense:1};active=true;submenu='';defending=false;enemyMax=currentEnemy.hp;enemyHp=enemyMax;maxHp=p.maxHp||100;hp=p.hp??maxHp;maxMp=p.maxMp||30;mp=p.mp??maxMp;stats={attack:p.attack||12,defense:p.defense||3};drawHero();drawEnemy();battle.classList.add('open');battle.style.setProperty('display','grid','important');battle.style.setProperty('visibility','visible','important');const bottom=battle.querySelector('.battlebottom');if(bottom)bottom.style.setProperty('display','grid','important');if(commands){commands.style.setProperty('display','grid','important');commands.style.setProperty('visibility','visible','important');commands.style.setProperty('opacity','1','important')}document.querySelector('.battlehead').textContent='COMBATE · '+currentEnemy.name.toUpperCase()+' · NV. '+currentEnemy.level;say('Um '+currentEnemy.name+' Nv. '+currentEnemy.level+' bloqueia o caminho! O que Yuu fará?');render();if(commands){commands.querySelectorAll('button').forEach(b=>{b.style.setProperty('display','block','important');b.style.setProperty('visibility','visible','important');b.style.setProperty('pointer-events','auto','important')})}}
window.lumenBattle={start,action:(k)=>act(k),refresh:render};
function close(){active=false;submenu='';defending=false;window.__lumenRewardUntil=0;window.__lumenRewardMessage='';window.__lumenProximityLock=true;if(window.lumenGame&&window.lumenGame.resetMovement)window.lumenGame.resetMovement();battle.classList.remove('open');battle.style.setProperty('display','none','important');battle.style.setProperty('visibility','hidden','important');battle.style.setProperty('pointer-events','none','important');if(commands)commands.innerHTML='';document.querySelector('#game')?.focus()}
function gameOver(){active=false;sync();battle.classList.remove('open');let screen=document.querySelector('#gameOverScreen');if(!screen){screen=document.createElement('div');screen.id='gameOverScreen';screen.style.cssText='position:fixed;inset:0;z-index:9999;display:grid;place-items:center;padding:20px;background:#070b16f5;color:#edf3ff;text-align:center;font-family:ui-monospace,monospace';screen.innerHTML='<div style="padding:32px 24px;border:3px solid #b94e68;background:#17243b"><h1>GAME OVER</h1><p>Yuu foi derrotada na floresta.</p><button id="restartGame">Começar de novo</button></div>';document.body.appendChild(screen);screen.querySelector('#restartGame').onclick=()=>location.reload()}screen.style.display='grid'}
function win(){if(!active)return;const before=state();active=false;submenu='';sync();let defeated=false;try{defeated=!!window.lumenGame?.defeatNearestEnemy?.(currentEnemy)}catch(err){console.error('Falha ao registrar vitória:',err)}const after=state();const gold=Math.max(0,(after.coins||0)-(before.coins||0));const xp=Math.max(0,(after.xp||0)-(before.xp||0));let text='VITÓRIA! '+currentEnemy.name+' derrotado!'+(defeated?' +'+gold+' cristais e +'+xp+' EXP.':' A vitória foi registrada; recompensas serão atualizadas ao retornar.');if((after.level||1)>(before.level||1)){const unlocked=spells.find(s=>s.level===after.level);text+=' SUBIU PARA O NÍVEL '+after.level+'! Habilidade desbloqueada: '+(unlocked?unlocked.name:'novas habilidades mágicas')+'.';}say(text);battle.style.setProperty('display','grid','important');battle.style.setProperty('visibility','visible','important');render();if(commands){commands.innerHTML='<div style="grid-column:1/-1;padding:12px;color:#fff0bd;font-weight:bold">'+text+'</div>';commands.style.setProperty('display','grid','important')}window.__lumenRewardMessage=text;window.__lumenRewardUntil=Date.now()+2600;setTimeout(()=>{if(!active)close()},2600)}
function enemyTurn(){if(!active)return;if(enemyHp<=0){win();return}const raw=(currentEnemy.attack||5)+Math.floor(Math.random()*5),dmg=Math.max(1,Math.floor(raw*(defending ? 0.3 : 1))-stats.defense);defending=false;hp=Math.max(0,hp-dmg);sync();say(currentEnemy.name+' ataca e causa '+dmg+' de dano'+(dmg<raw?'! Defesa reduziu o golpe.':'!'));render();if(hp<=0)gameOver();else setTimeout(()=>{if(active){submenu='';say('Sua vez! Escolha um comando.');render()}},450)}
function afterAction(){render();if(enemyHp<=0)win();else setTimeout(enemyTurn,650)}
function act(k){if(!active)return;if(k==='attack'){submenu='';const dmg=Math.max(1,stats.attack+Math.floor(Math.random()*5)-(currentEnemy.defense||0));enemyHp-=dmg;say('Yuu ataca e causa '+dmg+' de dano!');afterAction()}else if(k==='defend'){submenu='';defending=true;say('Yuu se defende. O próximo ataque causará menos dano.');setTimeout(enemyTurn,350)}else if(k==='abilities'){submenu='abilities';say('Escolha uma magia. Você aprende uma nova a cada nível.');render()}else if(k==='items'){submenu='items';say('Escolha uma poção para usar.');render()}else if(k==='back'){submenu='';say('Sua vez! Escolha um comando.');render()}else if(k==='escape'){submenu='';say('Yuu escapou do combate com sucesso!');setTimeout(close,250)}}
function cast(n){const spell=spells.find(s=>s.level===n),p=state();if(!spell||spell.level>(p.level||1))return;if(mp<spell.cost){say('MP insuficiente para '+spell.name+'!');return}mp-=spell.cost;sync();const dmg=Math.max(2,spell.damage+Math.floor(Math.random()*7)-(currentEnemy.defense||0));enemyHp-=dmg;submenu='';say('✧ '+spell.name+' causa '+dmg+' de dano mágico!');afterAction()}
function item(type){const p=state();if(type==='life'){if(!p.potions||hp>=maxHp||!window.lumenGame?.usePotion?.()){say('Não é possível usar uma poção de vida agora.');return}hp=state().hp;say('Poção de vida usada! Vitalidade recuperada.')}else{if(!(window.lumenShop?.inventory?.manaPotions)||mp>=maxMp||!window.lumenGame?.useManaPotion?.()){say('Não é possível usar uma poção de mana agora.');return}mp=state().mp;say('Poção de mana usada! Mana recuperada.')}submenu='';sync();afterAction()}
commands.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||b.disabled)return;if(!b.dataset.action&&!b.dataset.spell&&!b.dataset.item)return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();if(b.dataset.action)act(b.dataset.action);else if(b.dataset.spell)cast(Number(b.dataset.spell));else if(b.dataset.item)item(b.dataset.item)},true);
document.querySelector('#attack').onclick=()=>start();document.querySelector('#potion').onclick=()=>{if(active)act('items');else start()};
window.addEventListener('keydown',e=>{const k=e.key.toLowerCase();if(!active){if(k===' '||k==='j'){e.preventDefault();e.stopImmediatePropagation();start()}return}if([' ','escape','enter','1','2','3','4','5','6'].includes(k)){e.preventDefault();e.stopImmediatePropagation();if(submenu==='abilities'&&/^[1-6]$/.test(k)){cast(Number(k));return}if(submenu==='items'&&(k==='1'||k==='2')){item(k==='1'?'life':'mana');return}if(k==='1')act('attack');else if(k==='2')act('defend');else if(k==='3')act('abilities');else if(k==='4')act('items');else if(k==='5'||k==='escape')act('escape');else if(k==='escape'&&submenu)act('back')}else{e.preventDefault();e.stopImmediatePropagation()}},true);
drawHero();drawEnemy()
})();