(()=>{'use strict';
const $=s=>document.querySelector(s),overlay=$('#rpgMenu'),content=$('#rpgContent'),toast=$('#rpgToast');
if(!overlay||!content)return;
let tab='character',selectedSlot='weapon';
const slotInfo={
weapon:{label:'Arma',icon:'⚔',item:'staff',name:'Cajado de âmbar',desc:'Arma mágica · +5 de poder de ataque.'},
armor:{label:'Armadura',icon:'◈',item:'robe',name:'Manto lunar',desc:'Armadura lunar · +20 de vitalidade máxima.'},
accessory:{label:'Acessório',icon:'✧',item:null,name:'Acessório',desc:'Nenhum acessório encontrado.'},
relic:{label:'Relíquia',icon:'◇',item:null,name:'Relíquia',desc:'Nenhuma relíquia encontrada.'}
};
function state(){return window.lumenGame?.getState?.()||{hp:100,maxHp:100,xp:0,level:1,coins:12,potions:1}}
function inv(){return window.lumenShop?.inventory||{weapon:false,armor:false,potions:0,equippedWeapon:false,equippedArmor:false}}
function say(t){if(toast)toast.textContent=t}
function open(){overlay.classList.add('open');overlay.setAttribute('aria-hidden','false');render()}
function close(){overlay.classList.remove('open');overlay.setAttribute('aria-hidden','true')}
function render(){document.querySelectorAll('.rpg-tabs [data-tab]').forEach(b=>b.classList.toggle('selected',b.dataset.tab===tab));if(tab==='character')renderCharacter();if(tab==='consumables')renderConsumables();if(tab==='equipment')renderEquipment()}
function renderCharacter(){const p=state(),bag=inv(),attack=10+(bag.equippedWeapon?5:0);content.innerHTML='<div class="menu-character"><div class="character-card"><canvas id="menuPortrait" width="256" height="256"></canvas><strong>Yuu, Andarilha</strong><small>Maga errante · Nível '+p.level+'</small></div><div class="character-details"><div class="detail-tile"><span>♥ VITALIDADE</span><b>'+p.hp+' / '+p.maxHp+'</b><div class="detail-sub">Pontos de vida</div></div><div class="detail-tile"><span>✦ ATAQUE</span><b>'+attack+'</b><div class="detail-sub">'+(bag.equippedWeapon?'Cajado de âmbar equipado':'Equipamento básico')+'</div></div><div class="detail-tile"><span>✧ EXPERIÊNCIA</span><b>'+p.xp+' / '+p.level*30+'</b><div class="detail-sub">Próximo nível</div></div><div class="detail-tile"><span>✧ MANA</span><b>'+(p.mp??30)+' / '+(p.maxMp??30)+'</b><div class="detail-sub">Pontos de magia</div></div><div class="detail-tile"><span>◇ CRISTAIS</span><b>'+p.coins+'</b><div class="detail-sub">Moeda da floresta</div></div><div class="detail-tile"><span>♥ POÇÕES</span><b>'+p.potions+'</b><div class="detail-sub">Consumíveis na bolsa</div></div><div class="detail-tile"><span>◈ DEFESA</span><b>'+(bag.equippedArmor?'20':'0')+'</b><div class="detail-sub">'+(bag.equippedArmor?'Manto lunar':'Sem armadura')+'</div></div></div></div>';const source=$('#portrait'),target=$('#menuPortrait');if(source&&target){const c=target.getContext('2d');c.imageSmoothingEnabled=false;c.drawImage(source,0,0,256,256)}}
function renderConsumables(){const p=state();content.innerHTML='<h3 class="menu-section-title">CONSUMÍVEIS</h3><p class="menu-note">Itens de uso imediato. A bolsa começa quase vazia; poções podem ser compradas com o mercador.</p><div class="consumable-list"><div class="consumable-row"><div class="consumable-icon">♥</div><div><strong>Poção de vitalidade</strong><small>Recupera 45 HP. Estoque: '+p.potions+'.</small></div><button id="usePotion" '+(p.potions<1||p.hp>=p.maxHp?'disabled':'')+'>Usar</button></div><div class="consumable-row"><div class="consumable-icon" style="background:#252b45;color:#c4b8ff">✧</div><div><strong>Éter arcano</strong><small>Nenhuma unidade no inventário.</small></div><button disabled>Vazio</button></div></div>';const b=$('#usePotion');if(b)b.addEventListener('click',()=>{$('#potion').click();render();say('Poção utilizada.')})}
function hasItem(type){const b=inv();return type==='weapon'?b.weapon:type==='armor'?b.armor:false}
function equipped(type){const b=inv();return type==='weapon'?b.equippedWeapon:type==='armor'?b.equippedArmor:false}
function renderEquipment(){const slots=Object.entries(slotInfo).map(([key,s])=>{const owned=s.item&&hasItem(key),on=owned&&equipped(key);return '<button class="equipment-slot '+(on?'equipped':'')+'" data-slot="'+key+'"><span>'+s.icon+' '+s.label+'</span><strong>'+(on?s.name:owned?s.name:'Vazio')+'</strong><small>'+(on?'Equipado':owned?'Obtido · clique para ver':'Espaço livre')+'</small></button>'}).join('');const s=slotInfo[selectedSlot];let details='<h3 class="menu-section-title">BOLSA DE EQUIPAMENTOS</h3>';if(s.item&&hasItem(selectedSlot)){details+='<div class="bag-item"><div><span>'+s.name+'</span><small>'+s.desc+'</small></div><button id="equipToggle">'+(equipped(selectedSlot)?'Desequipar':'Equipar')+'</button></div>'}else{const owned=[['weapon','Cajado de âmbar','Arma mágica · +5 ataque'],['armor','Manto lunar','Armadura · +20 vitalidade máxima']].filter(([type])=>hasItem(type));if(owned.length){details+=owned.map(([type,name,desc])=>'<div class="bag-item"><div><span>'+name+'</span><small>'+desc+'</small></div><button data-equip-item="'+type+'">'+(equipped(type)?'Equipado':'Equipar')+'</button></div>').join('')}else details+='<p class="empty-bag">Sua bolsa está vazia. Encontre o mercador e interaja com ele para adquirir equipamentos.</p>'}content.innerHTML='<h3 class="menu-section-title">EQUIPAMENTOS</h3><p class="menu-note">Os espaços começam vazios. Selecione um espaço para consultar os itens que você já obteve.</p><div class="equipment-layout"><div class="equipment-slots">'+slots+'</div><div class="equipment-bag">'+details+'</div></div>';content.querySelectorAll('[data-slot]').forEach(b=>b.addEventListener('click',()=>{selectedSlot=b.dataset.slot;renderEquipment()}));const toggle=$('#equipToggle');if(toggle)toggle.addEventListener('click',()=>toggleEquipment(selectedSlot));content.querySelectorAll('[data-equip-item]').forEach(b=>b.addEventListener('click',()=>toggleEquipment(b.dataset.equipItem)))}
function toggleEquipment(type){const b=inv(),owned=type==='weapon'?b.weapon:b.armor;if(!owned){say('Esse espaço ainda está vazio. Visite o mercador para obter equipamentos.');return}const current=type==='weapon'?b.equippedWeapon:b.equippedArmor;window.lumenGame?.equip?.(type,!current);say(!current?'Equipamento colocado.':'Equipamento removido.');renderEquipment()}
document.querySelectorAll('.rpg-tabs [data-tab]').forEach(b=>b.addEventListener('click',()=>{tab=b.dataset.tab;render()}));
$('#rpgOpen')?.addEventListener('click',open);$('#rpgClose')?.addEventListener('click',close);
overlay.addEventListener('click',e=>{if(e.target===overlay)close()});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&overlay.classList.contains('open'))close();if(e.key.toLowerCase()==='m'&&!overlay.classList.contains('open'))open()});
$('#interactButton')?.addEventListener('click',()=>{window.dispatchEvent(new KeyboardEvent('keydown',{key:'e',bubbles:true}));window.dispatchEvent(new KeyboardEvent('keyup',{key:'e',bubbles:true}))});
window.lumenMenu={open,close,refresh:render};
})();